# Generated by Django 6.0.1 on 2026-01-28 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persistence', '0002_remove_sbuser_sb_users_budget_chk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginotp',
            name='phone',
            field=models.CharField(db_index=True, max_length=190),
        ),
        migrations.CreateModel(
            name='SbCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('cat_img', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category_for', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={   
                'db_table': 'sb_category',
                'indexes': [models.Index(fields=['status'], name='idx_sb_category_status')],
            },
        ),
        migrations.CreateModel(
            name='SbSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subcat_img', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='persistence.sbcategory')),
            ],
            options={
                'db_table': 'sb_subcategory',
            },
        ),
        migrations.CreateModel(
            name='SbProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=30, unique=True)),
                ('product_name', models.CharField(max_length=200)),
                ('sku_code', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('hsn_code', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('no_of_compartments', models.IntegerField(blank=True, null=True)),
                ('no_of_pockets', models.IntegerField(blank=True, null=True)),
                ('occasion', models.CharField(blank=True, max_length=120, null=True)),
                ('product_color', models.CharField(blank=True, max_length=120, null=True)),
                ('material_used_for', models.CharField(blank=True, max_length=150, null=True)),
                ('brand', models.CharField(blank=True, max_length=150, null=True)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('offer_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('breadth', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cat', models.ForeignKey(db_column='cat_id', on_delete=django.db.models.deletion.RESTRICT, to='persistence.sbcategory')),
                ('subcat', models.ForeignKey(blank=True, db_column='subcat_id', null=True, on_delete=django.db.models.deletion.RESTRICT, to='persistence.sbsubcategory')),
            ],
            options={
                'db_table': 'sb_products',
            },
        ),
        migrations.CreateModel(
            name='SbSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_code', models.CharField(max_length=30, unique=True)),
                ('plan_name', models.CharField(max_length=200)),
                ('plan_short_name', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('terms', models.TextField(blank=True, null=True)),
                ('products_per_month', models.IntegerField(default=0)),
                ('products_per_year', models.IntegerField(default=0)),
                ('allow_redownload', models.BooleanField(default=False)),
                ('initial_loyalty_points', models.IntegerField(default=0)),
                ('price_type', models.CharField(default='FIXED', max_length=30)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('add_on_category_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_earning', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_members_in_plan', models.IntegerField(default=0)),
                ('total_courses_in_plan', models.IntegerField(default=0)),
                ('free_category_count', models.IntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='persistence.state')),
            ],
            options={
                'db_table': 'sb_subscription',
            },
        ),
        migrations.CreateModel(
            name='SbSubscriptionBenefits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(db_column='subscription_id', on_delete=django.db.models.deletion.CASCADE, to='persistence.sbsubscription')),
            ],
            options={
                'db_table': 'sb_subscription_benefits',
            },
        ),
        migrations.CreateModel(
            name='SbSubscriptionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_group', models.CharField(max_length=40)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('file_path', models.CharField(max_length=500)),
                ('file_type', models.CharField(blank=True, max_length=30, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(db_column='subscription_id', on_delete=django.db.models.deletion.CASCADE, to='persistence.sbsubscription')),
            ],
            options={
                'db_table': 'sb_subscription_media',
            },
        ),
        migrations.CreateModel(
            name='SbProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('product_img', models.CharField(max_length=500)),
                ('image_type', models.CharField(max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='persistence.sbproduct')),
            ],
            options={
                'db_table': 'sb_product_media',
                'indexes': [models.Index(fields=['product'], name='idx_sb_prod_media_product_id'), models.Index(fields=['status'], name='idx_sb_product_media_status'), models.Index(fields=['image_type'], name='idx_sb_product_media_type'), models.Index(fields=['product', 'sort_order'], name='idx_sb_product_media_sort')],
            },
        ),
        migrations.AddIndex(
            model_name='sbsubcategory',
            index=models.Index(fields=['status'], name='idx_sb_subcategory_status'),
        ),
        migrations.AddIndex(
            model_name='sbsubcategory',
            index=models.Index(fields=['cat'], name='idx_sb_subcategory_cat_id'),
        ),
        migrations.AddIndex(
            model_name='sbsubcategory',
            index=models.Index(fields=['cat', 'status'], name='idx_sb_subcategory_cat_status'),
        ),
        migrations.AddConstraint(
            model_name='sbsubcategory',
            constraint=models.UniqueConstraint(fields=('cat', 'title'), name='sb_subcategory_cat_title_uniq'),
        ),
        migrations.AddIndex(
            model_name='sbproduct',
            index=models.Index(fields=['cat'], name='idx_sb_products_cat_id'),
        ),
        migrations.AddIndex(
            model_name='sbproduct',
            index=models.Index(fields=['subcat'], name='idx_sb_products_subcat_id'),
        ),
        migrations.AddIndex(
            model_name='sbproduct',
            index=models.Index(fields=['status'], name='idx_sb_products_status'),
        ),
        migrations.AddIndex(
            model_name='sbproduct',
            index=models.Index(fields=['created_at'], name='idx_sb_products_created_at'),
        ),
        migrations.AddIndex(
            model_name='sbproduct',
            index=models.Index(fields=['selling_price'], name='idx_sb_products_price'),
        ),
        migrations.AddIndex(
            model_name='sbproduct',
            index=models.Index(fields=['offer_price'], name='idx_sb_products_offer_price'),
        ),
        migrations.AddIndex(
            model_name='sbproduct',
            index=models.Index(fields=['product_name'], name='idx_sb_products_name'),
        ),
        migrations.AddConstraint(
            model_name='sbproduct',
            constraint=models.CheckConstraint(condition=models.Q(('selling_price__gte', 0)), name='sb_products_selling_price_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='sbproduct',
            constraint=models.CheckConstraint(condition=models.Q(('offer_price__isnull', True), ('offer_price__gte', 0), _connector='OR'), name='sb_products_offer_price_gte_0'),
        ),
        migrations.AddIndex(
            model_name='sbsubscription',
            index=models.Index(fields=['status'], name='idx_sb_subscription_status'),
        ),
        migrations.AddIndex(
            model_name='sbsubscription',
            index=models.Index(fields=['is_default'], name='idx_sb_subscription_is_default'),
        ),
        migrations.AddIndex(
            model_name='sbsubscription',
            index=models.Index(fields=['state'], name='idx_sb_subscription_state_id'),
        ),
        migrations.AddIndex(
            model_name='sbsubscription',
            index=models.Index(fields=['price_type'], name='idx_sb_subscription_price_type'),
        ),
        migrations.AddConstraint(
            model_name='sbsubscription',
            constraint=models.CheckConstraint(condition=models.Q(('products_per_month__gte', 0)), name='sb_subscription_products_per_month_gte_0'),
        ),
        migrations.AddIndex(
            model_name='sbsubscriptionbenefits',
            index=models.Index(fields=['subscription'], name='idx_sb_sub_benef_subscrip_id'),
        ),
        migrations.AddIndex(
            model_name='sbsubscriptionbenefits',
            index=models.Index(fields=['benefit_type'], name='idx_sb_sub_benefits_type'),
        ),
        migrations.AddIndex(
            model_name='sbsubscriptionbenefits',
            index=models.Index(fields=['status'], name='idx_sb_sub_benefits_status'),
        ),
        migrations.AddIndex(
            model_name='sbsubscriptionbenefits',
            index=models.Index(fields=['subscription', 'sort_order'], name='idx_sb_sub_benefits_sort'),
        ),
        migrations.AddIndex(
            model_name='sbsubscriptionmedia',
            index=models.Index(fields=['subscription'], name='idx_sb_sub_media_subscrip_id'),
        ),
        migrations.AddIndex(
            model_name='sbsubscriptionmedia',
            index=models.Index(fields=['media_group'], name='idx_sb_sub_media_group'),
        ),
        migrations.AddIndex(
            model_name='sbsubscriptionmedia',
            index=models.Index(fields=['status'], name='idx_sb_sub_media_status'),
        ),
        migrations.AddIndex(
            model_name='sbsubscriptionmedia',
            index=models.Index(fields=['subscription', 'media_group', 'sort_order'], name='idx_sb_sub_media_sort'),
        ),
    ]
